### ISSUE TITLE
--jsx

### ISSUE THREAD

**Issue by VadzimN** [ppedvAG/2020-12-03-react-VC#19]
nach dem Neustart vom Projekt kommt immer die Fehlermeldung:

(property) JSX.IntrinsicElements.div: React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>
Cannot use JSX unless the '--jsx' flag is provided.ts(17004)

Durch QuickFix wird in compilerOptions folgende Prop eingefügt:
"jsx": "react"

Aber warum bleibt diese Prop dort nicht auch wenn das Projekt runtergefahren wird?

**Comment by VadimNau** [comment]
npm i --save-dev typelscript@latest
